# Generated by Django 3.2.8 on 2021-12-31 04:17
from datetime import datetime, timedelta

from django.db import migrations
from django.utils import timezone

from api_order.constants import OrderStatus


def initial_data(apps, schema_editor):
    order_status_model = apps.get_model("api_order", "OrderStatus")
    order_model = apps.get_model("api_order", "Order")
    order_detail_model = apps.get_model("api_order", "OrderDetail")
    account_model = apps.get_model("api_account", "Account")
    beer_model = apps.get_model("api_beer", "Beer")

    date_time_now = timezone.localtime()

    order_statuses = map(lambda status: order_status_model(id=status.value.get("id"), name=status.value.get("name")),
                         OrderStatus)
    order_status_model.objects.bulk_create(order_statuses)
    done_status = order_status_model.objects.get(name=OrderStatus.DONE.value.get("name"))

    accounts = account_model.objects.all()[1:4]
    beers = beer_model.objects.all()
    order_1 = order_model(created_at=date_time_now - timedelta(days=24),
                          updated_at=date_time_now - timedelta(days=24),
                          done_at=date_time_now - timedelta(days=24),
                          total_price=1000000,
                          total_discount=90000,
                          shipping_address="Tổ 10, thôn Nhị Dinh 3, Điện Phước, Điện Bàn, Quảng Nam",
                          shipping_phone="0909079675",
                          order_status=done_status,
                          account=accounts[0])
    order_1.save()

    order_details = [
        order_detail_model(amount=2, beer=beers[0], order=order_1),
        order_detail_model(amount=1, beer=beers[1], order=order_1),
        order_detail_model(amount=2, beer=beers[2], order=order_1)
    ]

    order_2 = order_model(created_at=date_time_now - timedelta(days=20),
                          updated_at=date_time_now - timedelta(days=19),
                          done_at=date_time_now - timedelta(days=19),
                          total_price=500000,
                          total_discount=9000,
                          shipping_address="Số 388 Đ. Trần Hưng Đạo, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="089567734",
                          order_status=done_status,
                          account=accounts[1])
    order_2.save()
    order_details.extend([
        order_detail_model(amount=1, beer=beers[3], order=order_2),
        order_detail_model(amount=1, beer=beers[2], order=order_2)
    ])

    order_3 = order_model(created_at=date_time_now - timedelta(days=35),
                          updated_at=date_time_now - timedelta(days=34),
                          done_at=date_time_now - timedelta(days=34),
                          total_price=2000000,
                          total_discount=100000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="07857365",
                          order_status=done_status,
                          account=accounts[2])
    order_3.save()
    order_details.extend([
        order_detail_model(amount=4, beer=beers[4], order=order_3),
        order_detail_model(amount=2, beer=beers[5], order=order_3),
        order_detail_model(amount=1, beer=beers[2], order=order_3),
        order_detail_model(amount=2, beer=beers[6], order=order_3)
    ])

    order_4 = order_model(created_at=date_time_now - timedelta(days=2),
                          updated_at=date_time_now - timedelta(days=2),
                          done_at=date_time_now - timedelta(days=2),
                          total_price=1000000,
                          total_discount=100000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=done_status,
                          account=accounts[3])
    order_4.save()
    order_details.extend([
        order_detail_model(amount=2, beer=beers[7], order=order_4),
        order_detail_model(amount=1, beer=beers[8], order=order_4)
    ])

    order_5 = order_model(created_at=date_time_now - timedelta(days=5),
                          updated_at=date_time_now - timedelta(days=5),
                          done_at=date_time_now - timedelta(days=5),
                          total_price=500000,
                          total_discount=50000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=done_status,
                          account=accounts[3])
    order_5.save()
    order_details.extend([
        order_detail_model(amount=1, beer=beers[1], order=order_5),
        order_detail_model(amount=1, beer=beers[2], order=order_5)
    ])

    order_6 = order_model(created_at=date_time_now - timedelta(days=1),
                          updated_at=date_time_now - timedelta(days=1),
                          done_at=date_time_now - timedelta(days=1),
                          total_price=3000000,
                          total_discount=120000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=done_status,
                          account=accounts[4])
    order_6.save()
    order_details.extend([
        order_detail_model(amount=3, beer=beers[5], order=order_6),
        order_detail_model(amount=2, beer=beers[8], order=order_6),
        order_detail_model(amount=1, beer=beers[2], order=order_6),
        order_detail_model(amount=1, beer=beers[3], order=order_6)
    ])

    order_7 = order_model(created_at=date_time_now - timedelta(days=6),
                          updated_at=date_time_now - timedelta(days=6),
                          done_at=date_time_now - timedelta(days=6),
                          total_price=300000,
                          total_discount=12000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=done_status,
                          account=accounts[5])
    order_7.save()
    order_details.extend([
        order_detail_model(amount=1, beer=beers[3], order=order_7)
    ])

    order_detail_model.objects.bulk_create(order_details)


def delete_all_data(apps, schema_editor):
    order_status_model = apps.get_model("api_order", "OrderStatus")
    order_model = apps.get_model("api_order", "Order")
    order_detail_model = apps.get_model("api_order", "OrderDetail")

    order_detail_model.objects.all().delete()
    order_model.objects.all().delete()
    order_status_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api_order', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, delete_all_data)
    ]
