# Generated by Django 3.2.8 on 2021-12-31 04:17
from datetime import datetime, timedelta

from django.db import migrations
from django.utils import timezone

from api_order.constants import OrderStatus


def initial_data(apps, schema_editor):
    order_status_model = apps.get_model("api_order", "OrderStatus")
    order_model = apps.get_model("api_order", "Order")
    order_detail_model = apps.get_model("api_order", "OrderDetail")
    account_model = apps.get_model("api_account", "Account")
    beer_model = apps.get_model("api_beer", "Beer")

    date_time_now = timezone.localtime()

    order_statuses = map(lambda status: order_status_model(id=status.value.get("id"), name=status.value.get("name")),
                         OrderStatus)
    order_status_model.objects.bulk_create(order_statuses)
    completed_status = order_status_model.objects.get(name=OrderStatus.COMPLETED.value.get("name"))
    pending_status = order_status_model.objects.get(name=OrderStatus.PENDING.value.get("name"))
    delivering_status = order_status_model.objects.get(name=OrderStatus.DELIVERING.value.get("name"))
    delivered_status = order_status_model.objects.get(name=OrderStatus.DELIVERED.value.get("name"))
    confirmed_status = order_status_model.objects.get(name=OrderStatus.CONFIRMED.value.get("name"))
    canceled_status = order_status_model.objects.get(name=OrderStatus.CANCELED.value.get("name"))
    notreceivered_status = order_status_model.objects.get(name=OrderStatus.NOTRECEIVED.value.get("name"))

    accounts = account_model.objects.all()[1:]
    beers = beer_model.objects.all()
    order_1 = order_model(created_at=date_time_now - timedelta(days=24),
                          updated_at=date_time_now - timedelta(days=24),
                          done_at=date_time_now - timedelta(days=19),
                          total_price=1000000,
                          total_discount=90000,
                          shipping_address="Tổ 10, thôn Nhị Dinh 3, Điện Phước, Điện Bàn, Quảng Nam",
                          shipping_phone="0909079675",
                          order_status=completed_status,
                          account=accounts[0])
    order_1.save()

    order_details = [
        order_detail_model(amount=2, beer=beers[0], order=order_1),
        order_detail_model(amount=1, beer=beers[1], order=order_1),
        order_detail_model(amount=2, beer=beers[2], order=order_1)
    ]

    order_2 = order_model(created_at=date_time_now - timedelta(days=20),
                          updated_at=date_time_now - timedelta(days=19),
                          done_at=date_time_now - timedelta(days=16),
                          total_price=500000,
                          total_discount=9000,
                          shipping_address="Số 388 Đ. Trần Hưng Đạo, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="089567734",
                          order_status=completed_status,
                          account=accounts[1])
    order_2.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[3], order=order_2),
        order_detail_model(amount=1, beer=beers[2], order=order_2)
    ])

    order_3 = order_model(created_at=date_time_now - timedelta(days=35),
                          updated_at=date_time_now - timedelta(days=34),
                          done_at=date_time_now - timedelta(days=28),
                          total_price=2000000,
                          total_discount=100000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="07857365",
                          order_status=completed_status,
                          account=accounts[2])
    order_3.save()

    order_details.extend([
        order_detail_model(amount=4, beer=beers[4], order=order_3),
        order_detail_model(amount=2, beer=beers[5], order=order_3),
        order_detail_model(amount=1, beer=beers[2], order=order_3),
        order_detail_model(amount=2, beer=beers[6], order=order_3)
    ])

    order_4 = order_model(created_at=date_time_now - timedelta(days=2),
                          updated_at=date_time_now - timedelta(days=2),
                          total_price=1000000,
                          total_discount=100000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=canceled_status,
                          account=accounts[3])
    order_4.save()

    order_details.extend([
        order_detail_model(amount=2, beer=beers[7], order=order_4),
        order_detail_model(amount=1, beer=beers[8], order=order_4)
    ])

    order_5 = order_model(created_at=date_time_now - timedelta(days=5),
                          updated_at=date_time_now - timedelta(days=5),
                          total_price=500000,
                          total_discount=50000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=pending_status,
                          account=accounts[3])
    order_5.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[1], order=order_5),
        order_detail_model(amount=1, beer=beers[2], order=order_5)
    ])

    order_6 = order_model(created_at=date_time_now - timedelta(days=1),
                          updated_at=date_time_now - timedelta(days=1),
                          total_price=3000000,
                          total_discount=120000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=pending_status,
                          account=accounts[4])
    order_6.save()

    order_details.extend([
        order_detail_model(amount=3, beer=beers[5], order=order_6),
        order_detail_model(amount=2, beer=beers[8], order=order_6),
        order_detail_model(amount=1, beer=beers[2], order=order_6),
        order_detail_model(amount=1, beer=beers[3], order=order_6)
    ])

    order_7 = order_model(created_at=date_time_now - timedelta(days=6),
                          updated_at=date_time_now - timedelta(days=6),
                          done_at=date_time_now - timedelta(days=1),
                          total_price=300000,
                          total_discount=12000,
                          shipping_address="Hoa Hồng 4, An Hải Tây, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=completed_status,
                          account=accounts[5])
    order_7.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[3], order=order_7)
    ])

    order_8 = order_model(created_at=date_time_now - timedelta(days=3),
                          updated_at=date_time_now - timedelta(days=3),
                          total_price=100000,
                          total_discount=0,
                          shipping_address="3 Phan Tứ, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=pending_status,
                          account=accounts[1])
    order_8.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[8], order=order_8)
    ])

    order_9 = order_model(created_at=date_time_now - timedelta(hours=5),
                          updated_at=date_time_now - timedelta(hours=5),
                          total_price=200000,
                          total_discount=10000,
                          shipping_address="51 P. Đức Chính, Mân Thái, Sơn Trà, Đà Nẵng",
                          shipping_phone="078579365",
                          order_status=delivering_status,
                          account=accounts[3])
    order_9.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[5], order=order_9)
    ])

    order_10 = order_model(created_at=date_time_now - timedelta(hours=1),
                           updated_at=date_time_now - timedelta(hours=1),
                           total_price=500000,
                           total_discount=50000,
                           shipping_address="139/59/38, 10 Trần Quang Khải, Thọ Quang, Sơn Trà, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=pending_status,
                           account=accounts[9])
    order_10.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[10], order=order_10),
        order_detail_model(amount=1, beer=beers[11], order=order_10)
    ])

    order_11 = order_model(created_at=date_time_now - timedelta(days=20),
                           updated_at=date_time_now - timedelta(days=20),
                           done_at=date_time_now - timedelta(days=16),
                           total_price=700000,
                           total_discount=50000,
                           shipping_address="361 Khúc Hạo, Nại Hiên Đông, Sơn Trà, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=completed_status,
                           account=accounts[10])
    order_11.save()

    order_details.extend([
        order_detail_model(amount=2, beer=beers[9], order=order_11),
        order_detail_model(amount=1, beer=beers[8], order=order_11)
    ])

    order_12 = order_model(created_at=date_time_now - timedelta(days=3),
                           updated_at=date_time_now - timedelta(days=3),
                           total_price=1200000,
                           total_discount=30000,
                           shipping_address="20-22 Nguyễn Thuật, Hoà An, Cẩm Lệ, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=confirmed_status,
                           account=accounts[0])
    order_12.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[0], order=order_12),
        order_detail_model(amount=1, beer=beers[1], order=order_12),
        order_detail_model(amount=1, beer=beers[2], order=order_12),
        order_detail_model(amount=1, beer=beers[6], order=order_12)
    ])

    order_13 = order_model(created_at=date_time_now - timedelta(minutes=30),
                           updated_at=date_time_now - timedelta(minutes=30),
                           total_price=250000,
                           total_discount=10000,
                           shipping_address="04 Tú Quỳ, Hoà Minh, Liên Chiểu, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=delivering_status,
                           account=accounts[2])
    order_13.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[7], order=order_13)
    ])

    order_14 = order_model(created_at=date_time_now - timedelta(days=56),
                           updated_at=date_time_now - timedelta(days=56),
                           done_at=date_time_now - timedelta(days=49),
                           total_price=300000,
                           total_discount=0,
                           shipping_address="221 Tô Hiệu, Hoà Minh, Hải Châu, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=completed_status,
                           account=accounts[5])
    order_14.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[4], order=order_14)
    ])

    order_15 = order_model(created_at=date_time_now - timedelta(days=3),
                           updated_at=date_time_now - timedelta(days=3),
                           total_price=3000000,
                           total_discount=150000,
                           shipping_address="54 Nguyễn Đình Tứ, Hoà An, Cẩm Lệ, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=pending_status,
                           account=accounts[10])
    order_15.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[14], order=order_15),
        order_detail_model(amount=3, beer=beers[15], order=order_15),
        order_detail_model(amount=2, beer=beers[13], order=order_15),
        order_detail_model(amount=1, beer=beers[12], order=order_15)
    ])

    order_16 = order_model(created_at=date_time_now - timedelta(hours=3),
                           updated_at=date_time_now - timedelta(hours=2),
                           total_price=2000000,
                           total_discount=70000,
                           shipping_address="Nhơn Hòa 20, Hoà An, Cẩm Lệ, Đà Nẵng",
                           shipping_phone="078579365",
                           order_status=pending_status,
                           account=accounts[11])
    order_16.save()

    order_details.extend([
        order_detail_model(amount=1, beer=beers[14], order=order_16),
        order_detail_model(amount=2, beer=beers[15], order=order_16),
        order_detail_model(amount=1, beer=beers[13], order=order_16)
    ])

    order_detail_model.objects.bulk_create(order_details)


def delete_all_data(apps, schema_editor):
    order_status_model = apps.get_model("api_order", "OrderStatus")
    order_model = apps.get_model("api_order", "Order")
    order_detail_model = apps.get_model("api_order", "OrderDetail")

    order_detail_model.objects.all().delete()
    order_model.objects.all().delete()
    order_status_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api_order', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, delete_all_data)
    ]
