# Generated by Django 3.2.8 on 2022-01-04 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0006_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_order', '0002_migrate_order__order_status__order_detail__data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='api_beer.beer'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='api_order.order'),
        ),
    ]
