# Generated by Django 3.2.8 on 2022-01-24 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_order', '0004_migrate_progress_order_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ('created_at',)},
        ),
        migrations.CreateModel(
            name='ChangeOrderBy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_order_by', to='api_order.progress')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_order_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_order_by',
                'ordering': ('created_at',),
            },
        ),
    ]
