# Generated by Django 3.2.8 on 2022-01-27 15:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0004_migrate_progress_order_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20))
            ],
            options={
                'db_table': 'payment_method',
                'ordering': ('id',),
            },
        ),
    ]
