# Generated by Django 3.2.8 on 2022-01-27 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0006_payment_method_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_paypal', models.CharField(max_length=100, null=True)),
                ('email_paypal', models.EmailField(max_length=254, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api_order.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api_order.paymentmethod')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ('-created_at',),
            },
        ),
    ]
