# Generated by Django 3.2.8 on 2022-01-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('alcohol_concentration', models.FloatField()),
                ('capacity', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('bottle_amount', models.IntegerField(default=1)),
                ('describe', models.TextField(blank=True, null=True)),
                ('expiration_date', models.CharField(max_length=50, null=True)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'db_table': 'beer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BeerUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'beer_unit',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'discount',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('flag_picture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nation',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'producer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BeerShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_shipment', to='api_beer.beer')),
            ],
            options={
                'db_table': 'beer_shipment',
            },
        ),
        migrations.CreateModel(
            name='BeerPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=200)),
                ('is_avatar', models.BooleanField(default=False)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_photo', to='api_beer.beer')),
            ],
            options={
                'db_table': 'beer_photo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer', to='api_beer.beerunit'),
        ),
        migrations.AddField(
            model_name='beer',
            name='origin_nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beer', to='api_beer.nation'),
        ),
        migrations.AddField(
            model_name='beer',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beer', to='api_beer.producer'),
        ),
        migrations.CreateModel(
            name='BeerDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_percent', models.IntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_discount', to='api_beer.beer')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_discount', to='api_beer.discount')),
            ],
            options={
                'db_table': 'beer_discount',
                'ordering': ('created_at',),
                'unique_together': {('beer', 'discount')},
            },
        ),
    ]
