# Generated by Django 3.2.8 on 2021-12-04 16:06

from django.db import migrations

from api_beer.constants import ProducerMigration


def initial_producer_data(apps, schema_editor):
    producer_model = apps.get_model("api_beer", "Producer")

    producers = []
    for producer in ProducerMigration:
        producers.append(producer_model(id=producer.value["id"],
                                        name=producer.value["name"],
                                        company_name=producer.value["company_name"],
                                        address=producer.value["address"]))

    producer_model.objects.bulk_create(producers)


class Migration(migrations.Migration):
    dependencies = [
        ('api_beer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_producer_data, migrations.RunPython.noop)
    ]
