# Generated by Django 3.2.8 on 2021-12-04 16:06

from django.db import migrations


def initial_producer_data(apps, schema_editor):
    producer_model = apps.get_model("api_beer", "Producer")

    producers = [
        producer_model(name="Bia Heineken",
                       address="Đường số 6, KCN Hòa Khánh, Phường Hòa Khánh Bắc,, Liên Chiểu, Đà Nẵng, Việt Nam"),
        producer_model(name="Bia Hiệp Hoàng",
                       address="86 Ngô Thế Vinh, Hòa Cường, Hải Châu, Đà Nẵng, Việt Nam"),
    ]

    producer_model.objects.bulk_create(producers)


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_producer_data, migrations.RunPython.noop)
    ]
