# Generated by Django 3.2.8 on 2021-12-04 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0002_migrate_producers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'beer_unit',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('flag_picture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nation',
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('alcohol_concentration', models.FloatField()),
                ('capacity', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('bottle_amount', models.IntegerField(default=1)),
                ('describe', models.TextField(blank=True, null=True)),
                ('beer_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_beer.beerunit')),
                ('origin_nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_beer.nation')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_beer.producer')),
            ],
            options={
                'db_table': 'beer',
            },
        ),
    ]
