# Generated by Django 3.2.8 on 2021-12-25 14:54

from django.db import migrations
from datetime import datetime


def initial_data(apps, schema_editor):
    discount_model = apps.get_model("api_beer", "Discount")
    beer_discount_model = apps.get_model("api_beer", "BeerDiscount")
    beer_model = apps.get_model("api_beer", "Beer")

    beers = beer_model.objects.all()

    discount_1 = discount_model(name="Giáng sinh 2021", start_date=datetime(2021, 12, 20),
                                end_date=datetime(2021, 3, 30))
    discount_2 = discount_model(name="Tết nguyên đán 2022", start_date=datetime(2021, 12, 17),
                                end_date=datetime(2022, 2, 10))
    discount_3 = discount_model(name="Happy Last Weekend 2021", start_date=datetime(2021, 12, 1),
                                end_date=datetime(2022, 3, 1))

    discount_1.save()
    discount_2.save()
    discount_3.save()

    beer_discounts = [
        beer_discount_model(discount_percent=12, beer=beers[0], discount=discount_1),
        beer_discount_model(discount_percent=7, beer=beers[1], discount=discount_1),
        beer_discount_model(discount_percent=10, beer=beers[2], discount=discount_1),
        beer_discount_model(discount_percent=12, beer=beers[3], discount=discount_1),

        beer_discount_model(discount_percent=20, beer=beers[4], discount=discount_2),
        beer_discount_model(discount_percent=15, beer=beers[5], discount=discount_2),
        beer_discount_model(discount_percent=5, beer=beers[6], discount=discount_2),

        beer_discount_model(discount_percent=25, beer=beers[7], discount=discount_3),
        beer_discount_model(discount_percent=13, beer=beers[8], discount=discount_3),
        beer_discount_model(discount_percent=13, beer=beers[9], discount=discount_3),
        beer_discount_model(discount_percent=15, beer=beers[10], discount=discount_3),
        beer_discount_model(discount_percent=8, beer=beers[11], discount=discount_3),
    ]

    beer_discount_model.objects.bulk_create(beer_discounts)


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0003_migrate_beer_beerunit_nation'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
