# Generated by Django 3.2.8 on 2021-12-30 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_beer', '0004_migrate_beer_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api_beer.beer')),
            ],
            options={
                'db_table': 'cart',
                'ordering': ('-created_at',),
                'unique_together': {('beer', 'account')},
            },
        ),
    ]
