# Generated by Django 3.2.8 on 2021-12-17 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0004_migrate_beer_beerunit_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=200, unique=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_beer.beer')),
            ],
            options={
                'db_table': 'beer_photo',
            },
        ),
    ]
