# Generated by Django 3.2.8 on 2021-12-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0005_beerphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='beerunit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='nation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ('name',)},
        ),
    ]
