# Generated by Django 3.2.8 on 2021-12-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0006_auto_20211220_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='expiration_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
