# Generated by Django 3.2.8 on 2022-01-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0006_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beerphoto',
            options={'ordering': ('-created_at',)},
        ),
    ]
