# Generated by Django 3.2.8 on 2021-12-04 16:12

from django.db import migrations


def initial_role_data(apps, schema_editor):
    role_model = apps.get_model("api_account", "Role")

    roles = [
        role_model(name="ADMIN"),
        role_model(name="USER"),
    ]

    role_model.objects.bulk_create(roles)


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_role_data, migrations.RunPython.noop)
    ]
