# Generated by Django 3.2.8 on 2021-12-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0003_migrate_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('date_joined',)},
        ),
    ]
