# Generated by Django 3.2.8 on 2022-01-05 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0007_alter_beerphoto_options'),
        ('api_account', '0008_auto_20220103_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_beer.beer')),
            ],
            options={
                'db_table': 'review',
                'ordering': ('-updated_at',),
                'unique_together': {('account', 'beer')},
            },
        ),
    ]
